/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-final_mode
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_FINAL_MODE_API_H
#define INCLUDED_FINAL_MODE_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_final_mode_EXPORTS
#define FINAL_MODE_API __GR_ATTR_EXPORT
#else
#define FINAL_MODE_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_FINAL_MODE_API_H */
