/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-hackathon
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_HACKATHON_API_H
#define INCLUDED_HACKATHON_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_hackathon_EXPORTS
#define HACKATHON_API __GR_ATTR_EXPORT
#else
#define HACKATHON_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_HACKATHON_API_H */
